export const text = {
    title: 'Ahorra e invierte de manera inteligente',
    subTitle: 'Obtén cashback por tus compras y control total sobre tu dinero',
    registerBtn: 'Registrate',
    moreBtn: 'Saber más',
    whatHeading: '¿Qué es Giiri?',
    whatText: 'Somos una plataforma financiera que te permite ahorrar e invertir de manera inteligente. Te damos un porcentaje de devolución por tus compras en comercios aliados  que puedes invertir en proyectos rentables y haces crecer tu dinero.',
    howHeading: '¿Como funciona?',
    stepOne: 'Te registras',
    stepTwo: 'Defines tu meta de ahorro',
    stepTwoB: 'Defines tu meta',
    stepThree: 'Compras',
    stepFour: 'Inviertes',
    stepFive: 'Retiras dinero',
    startBtn: 'Comienza a ahorrar',
    whyHeading: '¿Por qué Giiri?',
    whyText: 'Somos la plataforma perfecta para aquellos que buscan una manera inteligente de mejorar su futuro financiero. Con Giiri obtenienes una devolución por tus compras, tienes control total sobre tu dinero y decides cómo hacerlo crecer. Además, nuestra plataforma es segura y fácil de usar.',
    joinHeading: 'Únete hoy!',
    joinText: '¿Quieres comenzar a ahorrar e invertir de manera inteligente? Únete a Giiri hoy y descubre cómo puedes hacerlo. Nuestra plataforma es segura y fácil de usar, y te permite controlar completamente tu dinero. ¡Regístrate ahora y comienza a ahorrar!',
    copy: '© Copyright 2023, All Rights Reserved by Giiri',
    logoA: '/assets/logo.png',
    heroImg: '/public/hero.png',
    video: '/public/video.png',
    menImg: '/public/men.png',
    girlImg: '/public/girl.png',
    girlBImg: '/public/girlB.png',
    logoB: '/public/logoFooterA.png',
    logoC: '/public/logoFooterB.png',
    facebook: '/public/facebook.svg',
    tiktok: '/public/tiktok.svg',
    instagram: '/public/instagram.svg',
}