export const text = {
    header: 'Ahorra e invierte de manera inteligente',
    subHeader: 'Obtén cashback por tus compras y control total sobre tu dinero',
    regBtn: 'Registrate',
    masBtn: 'Saber más',
    que: '¿Qué es Giiri?',
    queResp: 'Somos una plataforma financiera que te permite ahorrar e invertir de manera inteligente. Te damos un porcentaje de devolución por tus compras en comercios aliados  que puedes invertir en proyectos rentables y haces crecer tu dinero.',
    como: '¿Como funciona?',
    c1: 'Te registras',
    c2: 'Defines tu meta de ahorro',
    c3: 'Compras',
    c4: 'Inviertes',
    c5: 'Retiras dinero',
    porQue: '¿Por qué Giiri?',
    porQueResp: 'Somos la plataforma perfecta para aquellos que buscan una manera inteligente de mejorar su futuro financiero. Con Giiri obtenienes una devolución por tus compras, tienes control total sobre tu dinero y decides cómo hacerlo crecer. Además, nuestra plataforma es segura y fácil de usar.',
    unete: 'Únete hoy!',
    uneteResp: '¿Quieres comenzar a ahorrar e invertir de manera inteligente? Únete a Giiri hoy y descubre cómo puedes hacerlo. Nuestra plataforma es segura y fácil de usar, y te permite controlar completamente tu dinero. ¡Regístrate ahora y comienza a ahorrar!',
    copy: '© Copyright 2023, All Rights Reserved by Giiri',
    logoA: '/public/logo.png',
    heroImg: '/public/hero.png',
    vid: '/public/video.png',
    men: '/public/men.png',
    girl: '/public/girl.png',
    logoB: '/public/logoB.png',
    facebook: '/public/facebook.svg'
}